server:
  port: 9191

spring:
  application:
    name: load-product-service

#  datasource:
#    url: jdbc:postgresql://localhost:5432/fabrikka
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization : true # Ensures that the datasource is initialized after the application context is fully loaded
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


  sql:
    init:
      mode: always # Ensures that the schema is created on startup
      platform: h2 # Specifies the platform for SQL initialization

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/