server:
  port: 9191

spring:
  application:
    name: load-product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fabrikka
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/