server:
  port: 8082

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fabrikka
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rishavkumarthakur42@gmail.com
    password: jlvv xcdr otgu bbyv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
